#!/usr/bin/env bash

# One Time Setup 
if [ -d "/home/${SUDO_USER}/.dotfiles" ]; then
    cd && git clone https://github.com/SamuelDonovan/.dotfiles.git 
    mv /home/${SUDO_USER}/.bashrc ~/.bashrc.bkup
    [ -d "/home/${SUDO_USER}/.config" ] && mv /home/${SUDO_USER}/.config /home/${SUDO_USER}/.config.bkup
fi

# System Management 
pacman -S networkmanager --noconfirm --needed

# Desktop Environment
pacman -S wofi hyprland waybar python-pywal ttf-nerd-fonts-symbols --noconfirm --needed

# Tools 
pacman -S ripgrep --noconfirm --needed

# Editor
pacman -S nvim --noconfirm --needed

# Dotfile Orchestrator 
pacman -S stow --noconfirm --needed 
cd /home/${SUDO_USER}/.dotfiles && stow . --dotfiles 
source /home/${SUDO_USER}/.bashrc
